language: generic

services:
- docker

env:
  global:
    - secure: 'L6aCMFS3RUhbGwA0TdiOjXYAvtEWkQeX+p4jxU0kmyIjf6xVERNN3za2JuDL/3dkBPbgBskTbK766zP4k8tjuboTVQ1DkpZrc0HFy4bpBAxKNApNfVduQEb7uY3nnfaAdQLp1gse+Cv9GHEhLUNJIPnbAUjxVFGOY1cvUlwV5wI='

script:
- ./build.sh

deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
  on:
    repo: mdb/mikeball.info
    branch: master

notifications:
  email:
    on_success: never
    on_failure: always
