language: ruby

rvm:
  - 2.4.1

env:
  global:
    - secure: 'L6aCMFS3RUhbGwA0TdiOjXYAvtEWkQeX+p4jxU0kmyIjf6xVERNN3za2JuDL/3dkBPbgBskTbK766zP4k8tjuboTVQ1DkpZrc0HFy4bpBAxKNApNfVduQEb7uY3nnfaAdQLp1gse+Cv9GHEhLUNJIPnbAUjxVFGOY1cvUlwV5wI='

before_install:
  - npm install bower -g

install:
  - bower install
  - bundle install

script:
  - bundle exec middleman build

deploy:
  provider: script
  script: 'rvm 2.4.1 do bundle exec middleman s3_sync'
  skip_cleanup: true
  on:
    repo: mdb/mikeball.info
    branch: master

notifications:
  email:
    on_success: never
    on_failure: always
