language: node_js

node_js:
- 12.13.0

script:
- npm run build

env:
  global:
    - secure: 'L6aCMFS3RUhbGwA0TdiOjXYAvtEWkQeX+p4jxU0kmyIjf6xVERNN3za2JuDL/3dkBPbgBskTbK766zP4k8tjuboTVQ1DkpZrc0HFy4bpBAxKNApNfVduQEb7uY3nnfaAdQLp1gse+Cv9GHEhLUNJIPnbAUjxVFGOY1cvUlwV5wI='

deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
  on:
    repo: mdb/mikeball.info
    branch: master

notifications:
  email:
    on_success: never
    on_failure: always
