language: ruby

rvm:
  - 2.1.5

before_install:
  - npm install bower -g

install:
  - bower install
  - bundle install

script:
  - bundle exec rake
  - bundle exec middleman build

deploy:
  provider: script
  script: ci/deploy.sh
  skip_cleanup: true
  on:
    repo: mdb/mikeball.info
    branch: master

notifications:
  email:
    on_success: never
    on_failure: always
