languageCode = "en-us"
title = "Mike Ball"
theme = "mdb"

enableRobotsTXT = true

[params]
  description = "Personal information, recent projects, prints, and 15+ years of musings on technology and software engineering."
  robots = [
    "AdsBot-Google",
    "Amazonbot",
    "anthropic-ai",
    "Applebot",
    "Applebot-Extended",
    "AwarioRssBot",
    "AwarioSmartBot",
    "Bytespider",
    "CCBot",
    "ChatGPT",
    "ChatGPT-User",
    "Claude-Web",
    "ClaudeBot",
    "cohere-ai",
    "DataForSeoBot",
    "Diffbot",
    "FacebookBot",
    "Google-Extended",
    "GPTBot",
    "ImagesiftBot",
    "magpie-crawler",
    "omgili",
    "Omgilibot",
    "peer39_crawler",
    "PerplexityBot",
    "YouBot"
  ]

[permalinks]
  blog = "/blog/:title/"
  projects = "/projects/:title/"

[markup.goldmark.renderer]
  unsafe = true
