source 'http://rubygems.org'

gem 'rake'
gem 'middleman'
gem 'middleman-blog'
gem 'middleman-build-reporter'
gem 'nokogiri'
gem 'redcarpet'
gem 'middleman-syntax'
gem 'middleman-livereload', '~> 3.1.0'
gem 'pry'
gem 'rb-readline'
gem 'rspec'
gem 'capybara'
gem 'capybara-webkit', '1.14.0'
gem 'fog'
gem 'middleman-s3_sync'
