source 'https://rubygems.org'

gem 'rake'
gem 'middleman'
gem 'middleman-blog'
gem 'middleman-build-reporter'
gem 'redcarpet'
gem 'rouge'
gem 'middleman-syntax'
gem 'middleman-livereload', '~> 3.1.0'
gem 'pry'
gem 'rb-readline'
gem 'fog-aws'
gem 'middleman-s3_sync'
