source 'https://rubygems.org'

gem 'rake'
gem 'middleman'
gem 'middleman-blog'
gem 'middleman-sync'
gem 'nokogiri'
gem 'redcarpet'
gem 'middleman-syntax'
gem 'middleman-livereload', '~> 3.1.0'
gem 'pry'
gem 'rb-readline'
gem 'rspec'
gem 'capybara'
gem 'capybara-webkit'
