#
# Format:
#
# <stage name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   tag: <git tag pattern, optional>
#   repo: <git repository, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#

production:
  app: mdb
  stack: cedar #bamboo-ree-1.8.7
  tag: production/*
  FOO: bar
  config:
    BUNDLE_WITHOUT: "development:test"
    GOOGLE_ANALYTICS: "UA-12345678-1"

staging:
  stack: cedar
  app: mdb-staging
  config: &default
    BUNDLE_WITHOUT: "development:test"
    FOG_PROVIDER: "AWS"
    FOG_DIRECTORY: "clapclapexcitement"
    AWS_ACCESS_KEY: ""
    AWS_SECRET_KEY: ""
  addons:
    - pgbackups:auto-week
    - memcache:5mb
    - logging:basic
    - scheduler:standard

demo:
  app: mdb-demo
  config: *default
