name: Hello

on:
  repository_dispatch:

jobs:
  greet:
    if: github.event.action == "say-hello"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Say Hello
        run: echo "Hello, ${{ github.event.client_payload.name }}!"
