name: Hello

on:
  repository_dispatch:
    types: ["hello"]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Say-Hello
        run: echo "Hello, ${{ github.event.client_payload.name }}!"
